/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.Componente.*;
import restaurante.Componente.postre.*;

/**
 *
 * @author Estudiantes
 */
public class JFramePostre extends javax.swing.JFrame {

    /**
     * Creates new form JFramePostre
     */
    Componente alimento;
    Plato tipo;
    public static String a;
    
    public JFramePostre() {
        initComponents();
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        tipo = new Plato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jrbtnFrio = new javax.swing.JRadioButton();
        jrbtnCaliente = new javax.swing.JRadioButton();
        jrbtnFrito = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del postre");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jrbtnFrio.setText("Postre frio");
        jrbtnFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnFrioActionPerformed(evt);
            }
        });

        jrbtnCaliente.setText("Postre caliente");
        jrbtnCaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnCalienteActionPerformed(evt);
            }
        });

        jrbtnFrito.setText("Postre frito");
        jrbtnFrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnFritoActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el tipo del postre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtnFrito)
                    .addComponent(jrbtnCaliente)
                    .addComponent(jrbtnFrio))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtnFrio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtnCaliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtnFrito)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        tipo.guardarPosbe(alimento.guardar(jTextField1.getText()), alimento);
        a=tipo.mostrarPosbe();
        jrbtnFrito.setSelected(false);
        jrbtnCaliente.setSelected(false);
        jrbtnFrio.setSelected(false);
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jrbtnFrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnFrioActionPerformed
        jrbtnFrito.setSelected(false);
        jrbtnCaliente.setSelected(false);
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
        alimento = new PostreFrio();
    }//GEN-LAST:event_jrbtnFrioActionPerformed

    private void jrbtnCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnCalienteActionPerformed
        jrbtnFrio.setSelected(false);
        jrbtnFrito.setSelected(false);
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
        alimento = new PostreCaliente();
    }//GEN-LAST:event_jrbtnCalienteActionPerformed

    private void jrbtnFritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnFritoActionPerformed
        jrbtnFrio.setSelected(false);
        jrbtnCaliente.setSelected(false);
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
        alimento = new PostreFrito();
    }//GEN-LAST:event_jrbtnFritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePostre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrbtnCaliente;
    private javax.swing.JRadioButton jrbtnFrio;
    private javax.swing.JRadioButton jrbtnFrito;
    // End of variables declaration//GEN-END:variables
}
