/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.Componente.*;
import restaurante.Componente.bebida.*;

/**
 *
 * @author Estudiantes
 */
public class JFrameBebida extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBebida
     */
    Componente alimento;

    public JFrameBebida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jrbtnLicores = new javax.swing.JRadioButton();
        jrbtnJugos = new javax.swing.JRadioButton();
        jrbtnLimonada = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jrbtnAgua = new javax.swing.JRadioButton();
        jrbtnCervezas = new javax.swing.JRadioButton();
        jrbtnVinos = new javax.swing.JRadioButton();
        jrbtnGaseosas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbtnLicores.setText("Licores");
        jrbtnLicores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnLicoresActionPerformed(evt);
            }
        });

        jrbtnJugos.setText("Jugos");

        jrbtnLimonada.setText("Limonada");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jrbtnAgua.setText("Agua");

        jrbtnCervezas.setText("Cervezas");
        jrbtnCervezas.setEnabled(false);

        jrbtnVinos.setText("Vinos");
        jrbtnVinos.setEnabled(false);

        jrbtnGaseosas.setText("Gaseosas");
        jrbtnGaseosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnGaseosasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnAgua)
                            .addComponent(jrbtnLimonada))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnCervezas)
                            .addComponent(jrbtnVinos))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnLicores)
                            .addComponent(jrbtnGaseosas)
                            .addComponent(jrbtnJugos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jrbtnGaseosas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtnLicores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtnJugos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnLimonada)
                    .addComponent(jrbtnCervezas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnAgua)
                    .addComponent(jrbtnVinos))
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        alimento.guardar(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jrbtnGaseosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnGaseosasActionPerformed
        alimento = new Gaseosas();
        jrbtnLimonada.setSelected(false);
        jrbtnAgua.setSelected(false);
        jrbtnLicores.setSelected(false);
        jrbtnJugos.setSelected(false);
        jTextField1.setEnabled(true);
    }//GEN-LAST:event_jrbtnGaseosasActionPerformed

    private void jrbtnLicoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnLicoresActionPerformed
        jrbtnGaseosas.setSelected(false);
        jrbtnAgua.setSelected(false);
        jrbtnJugos.setSelected(false);
        jrbtnLimonada.setSelected(false);
        jrbtnCervezas.setEnabled(true);
        jrbtnVinos.setEnabled(true);
        jTextField1.setEnabled(true);
    }//GEN-LAST:event_jrbtnLicoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrbtnAgua;
    private javax.swing.JRadioButton jrbtnCervezas;
    private javax.swing.JRadioButton jrbtnGaseosas;
    private javax.swing.JRadioButton jrbtnJugos;
    private javax.swing.JRadioButton jrbtnLicores;
    private javax.swing.JRadioButton jrbtnLimonada;
    private javax.swing.JRadioButton jrbtnVinos;
    // End of variables declaration//GEN-END:variables
}
