/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import javax.swing.JFrame;
import restaurante.Componente.*;
import restaurante.Componente.platoFuerte.*;

/**
 *
 * @author Estudiantes
 */
public class JFrameIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form JFrameIngredientes
     * 
     */
    PlatoFuerte alimento;
    Plato tipo;
    public static String a;
    public JFrameIngredientes() {
        initComponents();
        jTextField1.setVisible(false);
        jLabel1.setVisible(false);
        tipo = new Plato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbtnProteina = new javax.swing.JRadioButton();
        jrbtnGranos = new javax.swing.JRadioButton();
        jrbtnVerdura = new javax.swing.JRadioButton();
        jrbtnFruta = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbtnProteina.setText("Proteina");
        jrbtnProteina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnProteinaActionPerformed(evt);
            }
        });

        jrbtnGranos.setText("Granos");
        jrbtnGranos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnGranosActionPerformed(evt);
            }
        });

        jrbtnVerdura.setText("Verdura");
        jrbtnVerdura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnVerduraActionPerformed(evt);
            }
        });

        jrbtnFruta.setText("Fruta");
        jrbtnFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnFrutaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrediente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbtnProteina, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnGranos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnVerdura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnFruta, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jrbtnProteina)
                .addGap(18, 18, 18)
                .addComponent(jrbtnGranos)
                .addGap(18, 18, 18)
                .addComponent(jrbtnVerdura)
                .addGap(18, 18, 18)
                .addComponent(jrbtnFruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtnProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnProteinaActionPerformed
        jrbtnFruta.setSelected(false);
        jrbtnGranos.setSelected(false);
        jrbtnVerdura.setSelected(false);
        jTextField1.setVisible(true);
        jLabel1.setVisible(true);
        alimento = new Proteina();
    }//GEN-LAST:event_jrbtnProteinaActionPerformed

    private void jrbtnGranosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnGranosActionPerformed
        jrbtnFruta.setSelected(false);
        jrbtnProteina.setSelected(false);
        jrbtnVerdura.setSelected(false);
        jTextField1.setVisible(true);
        jLabel1.setVisible(true);
        alimento = new Granos();
    }//GEN-LAST:event_jrbtnGranosActionPerformed

    private void jrbtnVerduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnVerduraActionPerformed
        jrbtnProteina.setSelected(false);
        jrbtnGranos.setSelected(false);
        jrbtnVerdura.setSelected(false);
        jTextField1.setVisible(true);
        jLabel1.setVisible(true);
        alimento = new Verdura();
    }//GEN-LAST:event_jrbtnVerduraActionPerformed

    private void jrbtnFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnFrutaActionPerformed
        jrbtnFruta.setSelected(false);
        jrbtnGranos.setSelected(false);
        jrbtnProteina.setSelected(false);
        jTextField1.setVisible(true);
        jLabel1.setVisible(true);
        alimento = new Fruta();
    }//GEN-LAST:event_jrbtnFrutaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        tipo.guardarPosbe(alimento.guardar(jTextField1.getText()), alimento);
        a=tipo.mostrarFuerte();
        jrbtnFruta.setSelected(false);
        jrbtnProteina.setSelected(false);
        jrbtnVerdura.setSelected(false);
        jrbtnGranos.setSelected(false);
        jTextField1.setVisible(false);
        jTextField1.setText("");
        jLabel1.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrbtnFruta;
    private javax.swing.JRadioButton jrbtnGranos;
    private javax.swing.JRadioButton jrbtnProteina;
    private javax.swing.JRadioButton jrbtnVerdura;
    // End of variables declaration//GEN-END:variables
}
